template header

name
attributeObject
conditional
actions
priority
active

package eubrazil.atmosphere.templates;

global eubr.atmosphere.tma.entity.qualitymodel.Attribute attribute

import java.text.SimpleDateFormat;
import eubrazil.atmosphere.planning.AdaptationManager;
import function eubrazil.atmosphere.util.drools.DroolsUtility.debug;

dialect "java"

template "Trustworthiness"

rule "@{name}" 
enabled @{active}
salience @{priority}
when
    @{attributeObject}(@{conditional})
then
    AdaptationManager.performAdaptation(@{actions});
	debug(drools);
end

end template